version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the python consumers
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    volumes:
      - ${PWD}:/app
    ports:
      - 5000:5000
    environment:
      - DEVELOPMENT=1
      - PYTHONUNBUFFERED=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  esdata1:
    driver: local
