version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the python consumers
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    depends_on:
      - elasticsearch
      - workspace
    volumes:
      - ${PWD}:/app
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DEVELOPMENT=1
      - PYTHONUNBUFFERED=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WORKSPACE_URL=http://workspace:5000

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - web
    volumes:
      - ${PWD}:/app

  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  # Mock workspace server (see src/test/mock_workspace/endpoints.json)
  workspace:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/test/mock_workspace:/config
